### ISSUE TITLE
详细说明代码意义

### ISSUE THREAD

**Issue by wangzaixiaolonggbao** [Ryhax/aco#1]
本人是初学者，正在学习蚁群算法三维实现的知识，但下载了作者的代码之后，有很多地方看不懂，例如如何实现障碍物自定义。希望作者能对每个文件做详细的注释，十分感谢

**Comment by Ryhax** [comment]
生成障碍物的部分：

**Comment by Ryhax** [comment]
hi！
已添加关键代码注释，谢谢支持。
Thanks！😋

**Comment by wangzaixiaolonggbao** [comment]
十分感谢！！
